#!/usr/bin/env bash
set -euo pipefail

cli_init_root=$(realpath ".")

# cdk_ansible_repo_root=../../cdk-ansible
cdk_ansible_repo_root=~/workdir/github.com/pollenjp/cdk-ansible

module_names=(
  'ansible\.builtin\.command'
  'ansible\.builtin\.debug'
  'ansible\.builtin\.shell'
)
module_regex=$(
  IFS='|'
  echo "${module_names[*]}"
)

pushd "$cdk_ansible_repo_root"
uv --project "$cli_init_root" run \
  cargo run --package cdk-ansible-cli -- \
  module --pkg-prefix 'cdkam' --output-dir "${cli_init_root}/crates" --module-name-regex "${module_regex}"
popd

stringify_cmd=(uv run python -c 'import sys; from shlex import join; print(join(sys.argv[1:]))')
playbook_command_str=$(
  "${stringify_cmd[@]}" \
    uv --project "${cli_init_root}" \
    run --directory "${cli_init_root}" \
    ansible-playbook -v
)
cargo run --package my-app -- deploy -P 3 --playbook-command "${playbook_command_str}" -i dev SampleStack
